name: Test compiling cpp Code.

on:
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Setup Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      
      - name: Install conan and python dependencies
        run:  |
              python -m pip install --upgrade pip
              pip install conan
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Installing stuff for qt
        run:  |
              sudo apt-get update
              sudo apt-get install libgl1-mesa-dev libxkbcommon-x11-0 libgtk2.0-dev nasm -y
      - name: build qt using conan
        run:  |
              conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
              conan install qt/5.15.2@bincrafters/stable -o qt:qt3d=True -o qt:qtcharts=True -o qt:qttools=True -g virtualrunenv --build missing


      - name: checkout repo
        run:  |
              https://github.com/iammix/GithubActionsCompileTestCpp.git

      - name: build with gcc and run
        run:  |
              cd GithubActionsCompileTestCpp
              gcc main.cpp
              ./a.out
      - name: build with CMAKE and run
        run:  |
              cd GithubActionsCompileTestCpp
              mkdir build
              cd build
              cmake ..
              make
              ls
              ./hello